### ISSUE TITLE
payment page doesn't wait to confirm payment has been received

### ISSUE THREAD

**Issue by outlawforlife** [moshthepitt/woocommerce-lipa-na-mpesa#1]
After entering the phone number and confirmation code and you press place order. The page automatically says successful order but in my account or in the admin section it says pending payment. The payment page should hold and let the user know if the payment has been received and then continue to complete the order unless this we be a problem when the full amount is not paid.

**Comment by babueli** [comment]
The plugin is amazing, But am also facing the same issue as @outlawforlife. Hi developer please assist me so that plugin can integrate with kopokopo..

**Comment by morgan4080** [comment]
Hi Babueli, did kopokopo solve the woocommerce order clearing? Or did you find a work around?

**Comment by babueli** [comment]
Hi @morgan4080 ,

Still i was not able to solve the issue am stuck. is it possible you can help me solve it?

**Comment by moshthepitt** [comment]
This works as intended.  It will remain "pending" until the IPN from KopoKopo is received.
