### ISSUE TITLE
Mpesa Paid Orders Marked as Cancelled

### ISSUE THREAD

**Issue by dmmabiria** [moshthepitt/woocommerce-lipa-na-mpesa#2]
Whenever a payment is made via Mpesa, once authenticated with kopokopo, it marked as cancelled! What could be the problem?

**Comment by moshthepitt** [comment]
Please change your Woocommerce settings for "Hold Stock (minutes)".

If the IPN from KopoKopo for whatever reason is not received before the set hold stock time, then Woocommerce will mark the order as cancelled.
